name: 🐛 Bug Report
description: Report a bug with the WHPH landing page
title: "[Bug]: "
labels: ["bug"]
assignees: ["ahmet-cetinkaya"]

body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What should have happened?
      placeholder: Expected behavior...
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser
      placeholder: Chrome, Firefox, Safari, etc.